#ifndef VIMOL_PLATFORM_H
#define VIMOL_PLATFORM_H

#define VIMOL_DEFAULT_FONT_WIN32  "consolas"
#define VIMOL_DEFAULT_FONT_OSX    "andalemono"
#define VIMOL_DEFAULT_FONT_OTHER  "liberationmono"

#define VIMOL_DATA_PREFIX_WIN32   "APPDATA"
#define VIMOL_DATA_PREFIX_OSX     "HOME"
#define VIMOL_DATA_PREFIX_OTHER   "HOME"

#if defined(__WIN32__) /* defined in SDL */
#define VIMOL_DEFAULT_FONT VIMOL_DEFAULT_FONT_WIN32
#define VIMOL_DATA_PREFIX VIMOL_DATA_PREFIX_WIN32
#elif defined(__MACOSX__) /* defined in SDL */
#define VIMOL_DEFAULT_FONT VIMOL_DEFAULT_FONT_OSX
#define VIMOL_DATA_PREFIX VIMOL_DATA_PREFIX_OSX
#else
#define VIMOL_DEFAULT_FONT VIMOL_DEFAULT_FONT_OTHER
#define VIMOL_DATA_PREFIX VIMOL_DATA_PREFIX_OTHER
#endif

#endif /* VIMOL_PLATFORM_H */
