.\"
.\" Copyright (c) 2013-2017 Ilya Kaliman
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.TH VIMOL 1 "February 13, 2017"
.SH NAME
vimol \- vimol is a fast and functional molecular viewer and editor
.SH SYNOPSIS
.B vimol
.RI [ file... ]
.SH DESCRIPTION
.B vimol
is a fast and functional molecular viewer and editor with vim-like
key bindings. Viewing and editing of
.B .PDB
and
.B .XYZ
file formats is supported.
.SH KEY BINDINGS
.TP
.B a
Add hydrogen atoms to selection.
.TP
.B b
Make bond between selected atoms.
.TP
.B B
Reset bonds in current window.
.TP
.B c
Center selection.
.TP
.B C
Center and fit selection to window.
.TP
.B d
Delete selection.
.TP
.B e
Clear selection.
.TP
.B f
Zoom in.
.TP
.B F
Rotate camera along the view axis in a counterclockwise direction.
.TP
.B g
Zoom out.
.TP
.B G
Rotate camera along the view axis in a clockwise direction.
.TP
.B h/Left
Rotate view left.
.TP
.B H/Shift-Left
Pan view left.
.TP
.B i
Toggle display of atom indices.
.TP
.B I
Toggle display of atom symbols.
.TP
.B j/Down
Rotate view down.
.TP
.B J/Shift-Down
Move view down.
.TP
.B k/Up
Rotate view up.
.TP
.B K/Shift-Up
Move view up.
.TP
.B l/Right
Rotate view right.
.TP
.B L/Shift-Right
Move view right.
.TP
.B m
Measure position/distance/angle/torsion depending on the number of
selected atoms.
.TP
.B o
Toggle display of the coordinate system origin/axes.
.TP
.B O
Move selection to coordinate origin.
.TP
.B [0-9]p
Paste atoms to current window.
.TP
.B q
Quit
.B vimol
prompting if there are unsaved changes.
.TP
.B Q
Quit
.B vimol
discarding unsaved changes.
.TP
.B [0-9]r
Start recording in register 0-9.
.TP
.B 123s
Select atom 123.
.TP
.B [0-9]t
Replay recording. A register from 0 to 9 can optionally be specified.
.TP
.B 123u
Unselect atom 123.
.TP
.B v
Hide selection.
.TP
.B V
Show all atoms.
.TP
.B w
Select whole molecule.
.TP
.B W
Select all water molecules.
.TP
.B x
Cut selection.
.TP
.B [0-9]y
Copy (yank) selection. Yank register from 0 to 9 can
optionally be specified.
.SH AUTHOR
Vimol is (c) 2013-2017 Ilya Kaliman
