.\"
.\" Copyright (c) 2013-2017 Ilya Kaliman
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: February 20 2017 $
.Dt VIMOL 1
.Os
.Sh NAME
.Nm vimol
.Nd a powerful molecular viewer and editor with vi-like controls.
.Sh SYNOPSIS
.Nm vimol
.Op Ar files
.Sh DESCRIPTION
.Nm
is a fast and functional molecular viewer and editor with vi-like controls.
Viewing and editing of PDB and XYZ file formats is supported.
Multi-frame file support is implemented for both formats.
.Sh KEY BINDINGS
The default key bindings are described below.
The following notation is used:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It S-
Shift key.
.It C-
Ctrl key.
.El
.Pp
Arrow keys are equivalent to [hjkl] keys.
An optional atom selection, (sel), can be used with some commands.
See the
.Sx SELECTIONS
section for more details.
.Bl -tag -width Ds -offset indent
.It (sel)a
Fill unsatisfied valencies of selected atoms with hydrogen atoms.
.It S-a
Select all hydrogen atoms.
.It (sel)b
Toggle a bond between two selected atoms.
.It (sel)c
Center selection.
.It (sel)S-c
Center and fit selection to window.
.It (sel)d or (sel)Delete
Delete selected atoms.
.It e
Clear selection.
.It f
Zoom in.
.It g
Zoom out.
.It [hjkl]
Rotate the camera.
.It S-[hjkl]
Move the camera.
.It S-[fg]
Rotate the camera along the view axis.
.It i
Toggle display of atom indices.
.It S-i
Toggle display of atom names.
.It (sel)m
Measure position, distance, angle, or torsion depending on the number of
selected atoms.
.It (sel)n
Select atoms within 4 angstrom sphere of selection.
.It o
Toggle display of the coordinate system origin and axes.
.It (sel)S-o
Move selection to the coordinate system origin.
.It p or C-v
Paste atoms to the current window.
.It q
Quit.
.It S-q
Quit discarding unsaved changes.
.It r
Start recording of issued commands.
.It 123s
Select atom with index 123.
Select an unselected atom with lowest index if no index is specified.
.It t
Replay last recording.
Period key (.) with count can be used to repeat many times after that.
.It 123u
Unselect atom with index 123.
Unselect last selected atom if no index is specified.
.It (sel)v
Hide selected atoms.
Atoms can be made visible again by pressing z.
.It (sel)w
Select whole molecule containing selected atoms.
.It S-w
Select all water molecules.
.It (sel)x or (sel)C-x
Cut selected atoms.
.It (sel)y or (sel)C-c
Copy selected atoms.
.It z
Show all hidden atoms.
.It C-a
Select all atoms.
.It C-[hjklfg]
Rotate selected atoms.
.It CS-[hjkl]
Move selected atoms.
.It C-r
Redo last change.
.It C-z
Undo last change.
.It 123.
Repeat last command 123 times.
.It =
Invert current selection.
.It Space
Toggle full screen mode.
.It `
Reset view.
.It \&[
Go to the previous frame.
.It \&]
Go to the next frame.
.It {
Go 100 frames backward.
.It }
Go 100 frames forward.
.It <
Switch to the previous window.
.It >
Switch to the next window.
.El
.Sh SELECTIONS
Atom selections,
.Ar sel ,
are specified in three ways.
.Pp
First, an explicit atom index can be specified using number keys [0-9].
This is useful with key combinations.
For example, by pressing 123w the whole molecule containing an atom
with index 123 is selected.
.Pp
The second way is to explicitly list indices on the command line (see the
.Sx COMMANDS
section).
The indices are separated by a space character.
Index ranges can be specified using colon ':', e.g., "2 3 6:8" specifies
atoms with indices 2, 3, 6, 7, 8.
Negative indices are used to count backwards starting from the last
index, i.e., -1 is the last atom.
Special character '*' selects all atoms.
.Pp
Finally, if no explicit index is specified and no command-line arguments are
listed, selected atoms in the current window are used.
.Sh COMMANDS
Below is the list of available commands.
Command mode is started by pressing the colon key (:).
Most of the commands are bound to a key for convenience (see the
.Sx KEY BINDINGS
section).
.Bl -tag -width Ds -offset indent
.It Ic \&?
Display version information.
.It Ic add-hydrogens Op Ar sel
Fill unsatisfied valencies of atoms in selection
.Ar sel
with hydrogen atoms.
.It Ic atom Op Ar element Op Ar x y z
Create an atom with coordinates
.Ar x y z .
The default is to create a carbon atom at coordinate origin.
.It Ic bind Ar key Op Ar command
Bind key to command.
Display current binding if
.Ar command
is not specified.
.It Ic bond Op Ar sel
Toggle bond between atoms in selection.
The selection
.Ar sel
must contain exactly two atoms.
.It Ic chain Op Ar n
Create a carbon chain of length
.Ar n .
The default
.Ar n
is 4.
.It Ic clo[se]
Close current window.
.It Ic clo[se]!
Close current window discarding unsaved changes.
.It Ic copy Op Ar sel
Copy atoms from selection
.Ar sel
to a copy-buffer.
.It Ic delete Op Ar sel
Delete atoms in selection
.Ar sel .
.It Ic first-window
.D1 (alias: Ic first )
Switch to the first window.
.It Ic frame Op Ar n
Go to a specific frame
.Ar n .
Count from the end if
.Ar n
is negative, i.e., -1 is the last frame.
.It Ic fullscreen
Toggle full screen mode.
.It Ic hide-selection Op Ar sel
Hide atoms specified by
.Ar sel .
.It Ic invert-selection
Invert current selection.
.It Ic last-window
.D1 (alias: Ic last )
Switch to the last window.
.It Ic measure Op Ar sel
Measure position, distance, angle, or torsion depending on the number of
atoms in selection.
.It Ic move-selection Ar x y z Op Ar sel
Move selection by the specified amount.
The displacement
.Ar x y z
is relative to camera coordinate system.
.It Ic move-selection-to Ar x y z Op Ar sel
Move selection center to the coordinates
.Ar x y z .
.It Ic open Op Ar path
.D1 (alias: Ic new )
Open file in a new window.
.It Ic next-frame Op Ar n
Switch to the next frame.
Number of frames to advance,
.Ar n ,
can optionally be specified.
The value of
.Ar n
can be negative.
.It Ic next-window
Switch to the next window.
.It Ic paste
Paste atoms from a copy-buffer to the current window.
.It Ic prev-window
Switch to the previous window.
.It Ic quit
.D1 (alias: Ic q )
Quit.
.It Ic quit!
.D1 (alias: Ic q! )
Quit discarding unsaved changes.
.It Ic record
Start recording of issued commands.
A recording can be replayed using
.Ic replay
command.
.It Ic redo
Redo last change.
.It Ic rename Ar name Op Ar sel
Set a new name for all atoms in selection.
.It Ic replay
Replay last recording.
.It Ic reset-bonds
Reset all bonds.
.It Ic ring Op Ar n
Create a carbon ring of size
.Ar n .
The default
.Ar n
is 6.
.It Ic rotate-selection Ar a b c Op Ar sel
Rotate selected atoms.
Rotation angles relative to the camera coordinate system are specified by
.Ar a b c .
.It Ic select Op Ar sel
Add atoms specified by
.Ar sel
to the current selection.
Select an unselected atom with lowest index if the argument is omitted.
.It Ic select-element Ar names
Select atoms of a particular type.
For example,
.Bd -literal -offset indent
select-element H N
.Ed
selects all hydrogen and nitrogen atoms.
.It Ic select-molecule Op Ar sel
Select whole containing molecule for each atom in selection.
.It Ic select-sphere Ar radius Op Ar sel
Select a sphere within a specified
.Ar radius
from each atom in selection
.Ar sel .
.It Ic select-water
Select all water molecules.
.It Ic select-x Op Ar x
Select atoms with x coordinate grater than
.Ar x .
Invert selection to get the complementary set of atoms.
This is useful for making solvation boxes.
The default
.Ar x
is 0.
.It Ic select-y Op Ar y
Select atoms with y coordinate grater than
.Ar y .
Invert selection to get the complementary set of atoms.
This is useful for making solvation boxes.
The default
.Ar y
is 0.
.It Ic select-z Op Ar z
Select atoms with z coordinate grater than
.Ar z .
Invert selection to get the complementary set of atoms.
This is useful for making solvation boxes.
The default
.Ar z
is 0.
.It Ic set Ar setting Op Ar value
Set the
.Ar setting
to a new value.
Current value is displayed if the second argument is omitted.
See the
.Sx SETTINGS
section for the list of available options.
.It Ic show-all
Show all hidden atoms.
.It Ic source Ar path
Execute commands from a file.
.It Ic toggle Ar setting
Toggle a boolean setting.
See the
.Sx SETTINGS
section for the list of available options.
.It Ic undo
Undo last change.
.It Ic unselect Op Ar sel
Unselect atoms specified by
.Ar sel .
Unselect last selected atom if the argument is omitted.
.It Ic view-center-selection Op Ar sel
Center selection in window.
.It Ic view-fit-selection Op Ar sel
Center and fit selection to window.
.It Ic view-move Ar x y z
Move the camera.
Arguments
.Ar x y z
specify a displacement.
.It Ic view-reset
Reset the view.
.It Ic view-rotate Ar a b c
Rotate the camera.
Arguments
.Ar a b c
specify rotation angles.
.It Ic view-zoom Ar factor
Change zoom.
.It Ic write Op Ar path
.D1 (alias: Ic w )
Write changes to a file.
Save to the current file if
.Ar path
is not specified.
.El
.Sh SETTINGS
The following settings control various aspects of
.Nm .
They can be changed using
.Ic set
and
.Ic toggle
commands.
.Bl -tag -width Ds -offset indent
.It Ic atom-size
.D1 (type: Ic float )
.It Ic atom-visible
.D1 (type: Ic boolean )
.It Ic bg-color
.D1 (type: Ic color )
.It Ic bond-size
.D1 (type: Ic float )
.It Ic bond-visible
.D1 (type: Ic boolean )
.It Ic id-color
.D1 (type: Ic color )
.It Ic id-font
.D1 (type: Ic string )
.It Ic id-font-size
.D1 (type: Ic float )
.It Ic id-visible
.D1 (type: Ic boolean )
.It Ic name-color
.D1 (type: Ic color )
.It Ic name-font
.D1 (type: Ic string )
.It Ic name-font-size
.D1 (type: Ic float )
.It Ic name-visible
.D1 (type: Ic boolean )
.It Ic origin-color
.D1 (type: Ic color )
.It Ic origin-font
.D1 (type: Ic string )
.It Ic origin-font-size
.D1 (type: Ic float )
.It Ic origin-line-width
.D1 (type: Ic float )
.It Ic origin-visible
.D1 (type: Ic boolean )
.It Ic selection-color
.D1 (type: Ic color )
.It Ic selection-size
.D1 (type: Ic float )
.It Ic statusbar-color
.D1 (type: Ic color )
.It Ic statusbar-error-color
.D1 (type: Ic color )
.It Ic statusbar-font
.D1 (type: Ic string )
.It Ic statusbar-font-size
.D1 (type: Ic string )
.It Ic statusbar-text-color
.D1 (type: Ic color )
.It Ic statusbar-visible
.D1 (type: Ic boolean )
.It Ic color-x
.D1 (type: Ic color )
.El
.Sh AUTHORS
.Nm
was developed by
.An Ilya Kaliman
